#!/bin/bash

# Worker Signal Creator
# Helper script for workers to create signals for the Forge Master

# Usage: ./create_signal.sh [instance_name] [message_type] [message]

INSTANCE_NAME=${1:-"worker"}
MESSAGE_TYPE=${2:-"update"}
MESSAGE=${3:-"No message provided"}
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

SIGNAL_FILE="./signals/${INSTANCE_NAME}_${MESSAGE_TYPE}_${TIMESTAMP}.md"

# Create signals directory if it doesn't exist
mkdir -p "./signals"

# Create signal file
cat > "$SIGNAL_FILE" << EOF
# Worker Signal: $MESSAGE_TYPE

**From:** $INSTANCE_NAME
**Type:** $MESSAGE_TYPE
**Timestamp:** $(date)
**Branch:** \$(git branch --show-current 2>/dev/null || echo "unknown")

## Message

$MESSAGE

## Status

- [ ] Task in progress
- [ ] Task completed
- [ ] Need assistance
- [ ] Ready for review

## Files Modified

(List any files changed)

## Next Steps

(What should happen next)

---
*Generated by $INSTANCE_NAME*
EOF

echo "📨 Signal created: $SIGNAL_FILE"
echo "🔨 Forge Master will process this signal on next monitor run"
echo ""
echo "Signal content:"
cat "$SIGNAL_FILE"